services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: db_billing_api_pro
    restart: always
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
